name: Scheduler test

on:
  workflow_dispatch:
  schedule:
    - cron: "3-59/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm scheduler
        run: echo "Scheduler works at $(date -u)"
