/* =========================================
   MSTR / BTC Derivatives Warning System
   SAFE / CAUTION / OVERHEATED / EXTREME

   Risk calculation:
   - ONLY uses riskScore / riskLevel
     generated by update_market_history.py
   - This file does NOT calculate its own score.
========================================= */

(function () {

  const WARNING_ID =
    "mnavWarningSection";

  const HISTORY_URL =
    "history.json?ts=" +
    Date.now();


  /* ---------------------------------------
     STYLE
  --------------------------------------- */

  function injectStyle() {

    if (
      document.getElementById(
        "mnavWarningStyle"
      )
    ) {
      return;
    }

    const style =
      document.createElement(
        "style"
      );

    style.id =
      "mnavWarningStyle";

    style.textContent = `

      #${WARNING_ID} {
        margin-top: 22px;
      }

      .warning-box {
        margin-top: 15px;
        padding: 20px 24px;
        border-radius: 12px;
        background: #101620;
        border: 1px solid
          rgba(255,255,255,.08);
      }

      .warning-main {
        display: flex;
        align-items: center;
        gap: 16px;
      }

      .warning-light {
        width: 24px;
        height: 24px;
        border-radius: 50%;
        flex-shrink: 0;
        box-shadow:
          0 0 18px currentColor;
      }

      .warning-title {
        font-size: 22px;
        font-weight: 900;
        letter-spacing: .5px;
      }

      .warning-score {
        margin-top: 3px;
        font-size: 12px;
        color: #7f8b9c;
      }

      .warning-message {
        margin-top: 15px;
        padding-top: 14px;
        border-top:
          1px solid
          rgba(255,255,255,.07);
        color: #b9c2cf;
        font-size: 13px;
        line-height: 1.6;
      }

      .warning-grid {
        display: grid;
        grid-template-columns:
          repeat(4, 1fr);
        gap: 10px;
        margin-top: 14px;
      }

      .warning-card {
        padding: 12px;
        border-radius: 9px;
        background: #0d131c;
        border:
          1px solid
          rgba(255,255,255,.06);
      }

      .warning-label {
        font-size: 10px;
        color: #738093;
      }

      .warning-value {
        margin-top: 5px;
        font-size: 14px;
        font-weight: 800;
      }

      .warning-note {
        margin-top: 13px;
        font-size: 11px;
        color: #667386;
        line-height: 1.5;
      }

      .warning-source {
        margin-top: 10px;
        font-size: 10px;
        color: #596678;
      }

      @media (max-width: 700px) {

        .warning-grid {
          grid-template-columns:
            repeat(2, 1fr);
        }

      }

      @media (max-width: 600px) {

        .warning-box {
          padding: 18px;
        }

        .warning-title {
          font-size: 19px;
        }

      }

    `;

    document.head.appendChild(
      style
    );
  }


  /* ---------------------------------------
     SECTION
  --------------------------------------- */

  function createSection() {

    if (
      document.getElementById(
        WARNING_ID
      )
    ) {
      return;
    }

    const section =
      document.createElement(
        "section"
      );

    section.id =
      WARNING_ID;

    section.innerHTML = `

      <h2>
        🚦 BTC 레버리지 경고등
      </h2>

      <div
        id="warningContent"
        class="warning-box">

        데이터를 불러오는 중...

      </div>

    `;

    const historySection =
      document.getElementById(
        "mnavHistorySection"
      );

    if (historySection) {

      historySection.parentNode.insertBefore(
        section,
        historySection
      );

    } else {

      const footer =
        document.querySelector(
          "footer"
        );

      if (footer) {

        footer.parentNode.insertBefore(
          section,
          footer
        );

      } else {

        document.body.appendChild(
          section
        );

      }

    }
  }


  /* ---------------------------------------
     NUMBER
  --------------------------------------- */

  function number(value) {

    const n =
      Number(value);

    return Number.isFinite(n)
      ? n
      : null;
  }


  function fmt(
    value,
    digits = 2
  ) {

    const n =
      number(value);

    if (n === null) {
      return "—";
    }

    return n.toLocaleString(
      "en-US",
      {
        maximumFractionDigits:
          digits
      }
    );
  }


  /* ---------------------------------------
     LEVEL DISPLAY
  --------------------------------------- */

  function getLevelDisplay(
    level
  ) {

    const normalized =
      String(
        level || ""
      )
      .trim()
      .toUpperCase();


    if (
      normalized ===
      "EXTREME"
    ) {

      return {

        level:
          "EXTREME",

        symbol:
          "🔴",

        color:
          "#ff4d5a",

        message:
          "레버리지와 투기적 포지션이 동시에 과열된 구간입니다. 급격한 롱 청산과 변동성 확대 위험을 매우 높게 봐야 합니다."

      };

    }


    if (
      normalized ===
      "OVERHEATED"
    ) {

      return {

        level:
          "OVERHEATED",

        symbol:
          "🟠",

        color:
          "#ff9f43",

        message:
          "Funding과 OI를 중심으로 레버리지 과열 신호가 나타나고 있습니다. 추격매수는 조심하는 구간입니다."

      };

    }


    if (
      normalized ===
      "CAUTION"
    ) {

      return {

        level:
          "CAUTION",

        symbol:
          "🟡",

        color:
          "#f3c64e",

        message:
          "레버리지 시장에 부담이 조금씩 쌓이고 있습니다. 방향성이 강해지면 과열 단계로 빠르게 이동할 수 있습니다."

      };

    }


    if (
      normalized ===
      "SAFE"
    ) {

      return {

        level:
          "SAFE",

        symbol:
          "🟢",

        color:
          "#5ee6a8",

        message:
          "현재 확인되는 Funding, OI, BTC 가격 흐름에서는 뚜렷한 레버리지 과열 신호가 강하지 않습니다."

      };

    }


    return null;
  }


  /* ---------------------------------------
     DRAW
  --------------------------------------- */

  function draw(
    history
  ) {

    const content =
      document.getElementById(
        "warningContent"
      );

    if (!content) {
      return;
    }


    if (
      !Array.isArray(history) ||
      !history.length
    ) {

      content.innerHTML = `
        <div style="
          text-align:center;
          padding:20px;
          color:#788496;
        ">
          아직 데이터가 없습니다.
        </div>
      `;

      return;
    }


    const item =
      history[
        history.length - 1
      ];


    /* -----------------------------------
       IMPORTANT

       Risk Score는 여기서 계산하지 않는다.
       update_market_history.py가 만든 값을
       history.json에서 그대로 사용한다.
    ----------------------------------- */

    const score =
      number(
        item.riskScore
      );

    const storedLevel =
      String(
        item.riskLevel || ""
      )
      .trim()
      .toUpperCase();


    const display =
      getLevelDisplay(
        storedLevel
      );


    /* -----------------------------------
       Risk data missing
    ----------------------------------- */

    if (
      score === null ||
      !display
    ) {

      content.innerHTML = `

        <div class="warning-main">

          <div
            class="warning-light"
            style="
              color:#788496;
              background:#788496;
            ">
          </div>

          <div>

            <div
              class="warning-title"
              style="
                color:#788496;
              ">

              ⚪ DATA WAITING

            </div>

            <div
              class="warning-score">

              Risk Score:
              아직 계산되지 않았습니다.

            </div>

          </div>

        </div>


        <div
          class="warning-message">

          아직 Python 자동 업데이트에서
          Risk Score가 생성되지 않았습니다.
          데이터가 정상적으로 저장된 후
          경고등이 자동으로 표시됩니다.

        </div>


        <div
          class="warning-note">

          ※ 경고등은 history.json에 저장된
          공식 Risk Score만 사용합니다.
          브라우저에서 별도의 위험도 계산을
          수행하지 않습니다.

        </div>

      `;

      return;
    }


    /* -----------------------------------
       DRAW STORED RISK
    ----------------------------------- */

    content.innerHTML = `

      <div class="warning-main">

        <div
          class="warning-light"
          style="
            color:${display.color};
            background:${display.color};
          ">
        </div>

        <div>

          <div
            class="warning-title"
            style="
              color:${display.color};
            ">

            ${display.symbol}
            ${display.level}

          </div>

          <div
            class="warning-score">

            Risk Score:
            ${fmt(score, 1)}

          </div>

        </div>

      </div>


      <div class="warning-message">

        ${display.message}

      </div>


      <div class="warning-grid">

        <div
          class="warning-card">

          <div
            class="warning-label">

            Funding Rate

          </div>

          <div
            class="warning-value"
            style="
              color:#5ee6a8;
            ">

            ${
              number(
                item.fundingRate
              ) !== null

                ? fmt(
                    item.fundingRate,
                    4
                  ) + "%"

                : "—"
            }

          </div>

        </div>


        <div
          class="warning-card">

          <div
            class="warning-label">

            BTC OI

          </div>

          <div
            class="warning-value"
            style="
              color:#b56cff;
            ">

            ${
              number(
                item.oiBtc
              ) !== null

                ? fmt(
                    item.oiBtc
                  ) + " BTC"

                : "—"
            }

          </div>

        </div>


        <div
          class="warning-card">

          <div
            class="warning-label">

            OI 1D

          </div>

          <div
            class="warning-value">

            ${
              number(
                item.oiChange1dPct
              ) !== null

                ? (
                    number(
                      item.oiChange1dPct
                    ) >= 0
                      ? "+"
                      : ""
                  ) +
                  fmt(
                    item.oiChange1dPct,
                    1
                  ) +
                  "%"

                : "—"
            }

          </div>

        </div>


        <div
          class="warning-card">

          <div
            class="warning-label">

            BTC 1D

          </div>

          <div
            class="warning-value">

            ${
              number(
                item.btcChange1dPct
              ) !== null

                ? (
                    number(
                      item.btcChange1dPct
                    ) >= 0
                      ? "+"
                      : ""
                  ) +
                  fmt(
                    item.btcChange1dPct,
                    1
                  ) +
                  "%"

                : "—"
            }

          </div>

        </div>

      </div>


      <div
        class="warning-note">

        ※ 경고등은 단일 지표가 아니라
        Funding + OI + BTC 가격 모멘텀 +
        mNAV 등을 종합한 Python Risk Score를
        표시합니다. 투자 신호 자체는 아닙니다.

      </div>


      <div
        class="warning-source">

        Risk calculation:
        update_market_history.py
        → history.json

      </div>

    `;
  }


  /* ---------------------------------------
     LOAD
  --------------------------------------- */

  async function load() {

    try {

      const response =
        await fetch(
          HISTORY_URL,
          {
            cache:
              "no-store"
          }
        );


      if (
        !response.ok
      ) {

        throw new Error(
          "history.json " +
          response.status
        );

      }


      const history =
        await response.json();


      draw(history);


    } catch (error) {

      console.error(
        "Warning error:",
        error
      );


      const content =
        document.getElementById(
          "warningContent"
        );


      if (content) {

        content.innerHTML = `

          <div style="
            padding:20px;
            color:#788496;
          ">

            경고 데이터를
            불러오지 못했습니다.

          </div>

        `;

      }

    }

  }


  /* ---------------------------------------
     START
  --------------------------------------- */

  document.addEventListener(
    "DOMContentLoaded",
    () => {

      injectStyle();

      createSection();

      load();

    }
  );

})();
